Repository Edwardreyessp/encuestas-deploy, pull requests merged in 2022-10, with the labels that each got.

#21 Add FileUploader component
  .eslintrc.json
  package-lock.json
  package.json
  src/App.jsx
  src/components/utils/FileUploader.jsx
  src/components/visualizacion/Files.jsx
  src/routes/Muestreo.jsx
  yarn.lock
Labels: feature

#18 Lista de estratos
  src/components/utils/Estratos.jsx
Labels: feature

#19 Configuración de estratos
  src/components/utils/ConfigEstratos.jsx
Labels: feature

#25 Feat/file uploader
  src/components/utils/FileUploader.jsx
  src/components/utils/FileUploader.scss
  src/main.scss
Labels: feature

#24 Refactor/visualizacion
  src/components/utils/MyStepper.jsx
  src/components/visualizacion/Answer.jsx
  src/components/visualizacion/Answers.jsx
  src/components/visualizacion/Card.jsx
  src/components/visualizacion/Card.scss
  src/components/visualizacion/Cards.jsx
  src/components/visualizacion/Files.jsx
  src/components/visualizacion/Files.scss
  src/components/visualizacion/Question.jsx
  src/components/visualizacion/Questions.jsx
  src/components/visualizacion/Questions.scss
  src/routes/Visualizacion.jsx
  src/services/Index.js
Labels: refactor, feature

#27 Fix empty payload
  src/components/utils/FileUploader.jsx
  src/routes/Muestreo.jsx
Labels: bug
